### ISSUE TITLE
Some images can not optimized with method "upload" but with method "url"

### ISSUE THREAD

**Issue by crico** [kraken-io/kraken-node#11]
I'm testing Kraken to optimize multiple images. 

I tried it with images that work correctly using method **kraken.upload** but with others images, it doesn't work; the problem is that when **kraken.upload** is invoked and created request, no response, but I do not get any errors. 
I tried too the sames images with method **kraken.url** then it works correctly.

My code:

```javascript
        var options = {
            file: '/var/project/image-example.png',
            wait: true,
            lossy: true,
            resize: {
                width: maxWidth,
                strategy: 'landscape'
            }
        };

        var kraken = new Kraken({
            api_key: config.kraken.apiKey,
            api_secret: config.kraken.apiSecret
        });

        kraken.upload(options, function(data) {
            if (data.success) {
                console.log('Success. Optimized image URL: %s', data.kraked_url);
                deferred.resolve(data);
            } else {
                console.log('Fail. Error message: %s', data.error);
                deferred.resolve(null);
            }
        });
```

I'm debugging **kraken.js** node library and request seems ok, but I never get the response object. Any idea?

This is one example of these images: http://s18.postimg.org/fv8x7ttqh/unnamed.png

**Comment by matylla** [comment]
Fixed in 0.3.0
