### ISSUE TITLE
uploaded image from web form to s3

### ISSUE THREAD

**Issue by kingr** [kraken-io/kraken-node#12]
I can successfully load images to s3 when loading a local image from my machine using 'fs', however I can't seem to wrap my head around how to do this when uploading the images from a Web Form.

I'm using ExpressJs as my web server and would like to upload the image as a  Stream Object, the library clearly supports this from the docs.

With Multer-s3 I can upload to s3, but then loose the Kraken compression.

Can you guys steer me in the right direction to upload images to s3 using Kraken & Stream Objects?

**Comment by danielwyb** [comment]
@kingr did you find a solution?

**Comment by treyhuffine** [comment]
I'm having an issue for this as well. I'm using hapi as my server and create a `Readable` stream object but I keep getting a 502 error.

**Comment by treyhuffine** [comment]
@matylla would you be able to provide some feedback on what we could be doing wrong or an example on how to use a Stream object with kraken?

**Comment by danielwyb** [comment]
I got it. @treyhuffine 
The interface doesn't work - but sending your own post request works 👍 
`
const request = require('request')

request.post({
            url: 'https://api.kraken.io/v1/upload',
            json: true,
            strictSSL: false,
            formData: {
                data: JSON.stringify({
                    auth: {
                        api_key: krakenKey,
                        api_secret: krakenSecret
                    },
                    wait: true,
                    lossy: true
                }),
                file: {
                    value: imageBuffer,
                    options: {
                        filename: randomstring.generate(10) + '.png',
                        contentType: 'image/png'
                    }
                }
            }
        }, function optionalCallback(err, httpResponse, body) {
          if (err || !body.success) {
            console.log('error', err)
            resolve(imageBuffer)
          }
            console.log(body);

            request.defaults({encoding: null}).get(body.kraked_url, (err, res, body) => {
                resolve(err ? imageBuffer : body)
            })
        });`

**Comment by treyhuffine** [comment]
Thanks @danielwyb!

**Comment by treyhuffine** [comment]
@danielwyb - it looks like the only difference between your implementation and theirs is the object for the `Stream`, am I reading that correctly?

```
            file: {
                value: imageBuffer,
                options: {
                    filename: 'name.png',
                    contentType: 'image/png'
                }
            }
```

**Comment by danielwyb** [comment]
Yea, it's that there's a contentType provided so that it knows to interpret it as a png. @treyhuffine Btw, saw you're in SF. Moving there next week!

**Comment by treyhuffine** [comment]
Awesome, welcome to the area! My email is on my profile, feel free to message if you have any questions or want to connect when get here.

**Comment by human-a** [comment]
Did anyone solve this myth with stream objects? I don't have buffers available in my app, everything is a stream, and I keep getting the following error:

```{ success: false, message: 'No files found in the request' }```

I tried the kraken-node and node-fetch both gave me the same error back.
Currently, I have to work it out by saving the file in S3 and then optimizing and re-writing it back to S3 which is a bit redundant.

Any help is appreciated, the author of kraken seems to have abandoned it, and the krakne.io don't reply to support requests, even though we are paying them hundreds every month.

By the way, if anyone knows an alternative to kraken.io would be appreciated as well.
