### ISSUE TITLE
Set custom metadata on S3 uploads

### ISSUE THREAD

**Issue by goldfire** [kraken-io/kraken-node#15]
The S3 upload feature is great, but since we need to set cache-control headers on the files we upload, we still have to use the AWS-SDK to update the image after kraken has uploaded it. It would be great if this could be done in one step.

**Comment by matylla** [comment]
Hi @goldfire 

custom S3 metadata has been added to the Kraken.io API some time ago and it's currently also supported in kraken-node. Please have a look at our S3 docs here https://kraken.io/docs/storage-s3
