### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by tcrammond** [kraken-io/kraken-node#19]
Hi

Can you publish a new version to npm? #17 doesn't seem to be present in the latest release there, for example.

Thanks

**Comment by kingjerod** [comment]
You guys should publish a new version, not having error first callbacks is a rather big issue.

**Comment by ustuehler** [comment]
Version 0.4.0 has been released and officially includes error-first callbacks.

I have backed out #17 in the 0.3.x release series, because it was a breaking change, which accidentally got included in the 0.3.5 release (now deprecated and superseded by 0.3.6).
