### ISSUE TITLE
Make longer filenames possible

### ISSUE THREAD

**Issue by adamreisnz** [kraken-io/kraken-node#31]
Hello, we've been using this module successfully for a while now, but ran into the seemingly arbitrary limitation of 255 characters for a filename when passing a URL.

We sometimes directly pass avatars hosted on Google to process with Kraken, and these URL's can be quite long (> 255 characters).

Can you please remove or adjust this limitation to say 512 characters at least?

**Comment by nafetswirth** [comment]
Seeing the same issue using signed URLs from Firebase storage.

**Comment by adamreisnz** [comment]
This appears to have been fixed and addressed now.
