### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by BorisChumichev** [kraken-io/kraken-node#4]
Latest version of /lib/kraken.js file published on npm differs from the same file at this repository (despite they belong to the same package version). File on npm does not set 'Content-Type' header in Kraken.prototype.url method, so it causes 'Incoming request body does not contain a valid JSON object' error. Please update npm package.

**Comment by rdegges** [comment]
+1

**Comment by matylla** [comment]
Fixed in 0.3.0
