### ISSUE TITLE
Error pushing file to s3

### ISSUE THREAD

**Issue by quintonparker** [kraken-io/kraken-node#7]
Ever since upgrading to version 0.2.1 I've been getting "Error pushing file to s3" error when calling .url() method

I'm following the docs: https://github.com/kraken-io/kraken-node#amazon-s3-and-rackspace-cloud-files

But if I revert the node module to https://github.com/kraken-io/kraken-node/commit/bdaf51d3c4406c9563e70a605c9822c213a8b651 it works as expected

What am I doing wrong?

**Comment by matylla** [comment]
Fixed in 0.3.0
