### ISSUE TITLE
Error while pushing file to S3

### ISSUE THREAD

**Issue by tiefenb** [kraken-io/kraken-node#8]
Hi,

I get this error while pushing to S3.

{ message: 'Error while pushing file to S3: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.',
  success: false }

Please help me.

**Comment by tiefenb** [comment]
Maybe this happens only when hosting the S3 bucket on non US regions like Frankfurt.

I found out following: http://www.sitefinity.com/developer-network/forums/set-up-installation/amazon-s3---must-be-addressed-using-the-specified-endpoint

So if this is the problem, we should define the region in the request:

e.g.:

"s3_store": {
        "key": "",
        "secret": "",
        "bucket": "",
        "region": "eu-central-1"
    }

**Comment by kraken-io** [comment]
Hi @tiefenb,
yes, you need to always specify the region. We will update our docs soon.

**Comment by tiefenb** [comment]
hi, thank you.
I tried it and it works now.

Maybe you should write this to the documentation ;-)

https://github.com/kraken-io/kraken-node/blob/master/README.md

**Comment by kraken-io** [comment]
Yes, as mentioned we will update our docs soon.

**Comment by kraken-io** [comment]
Our Docs have been updated now. Sorry for the confusion.
