### ISSUE TITLE
multi-resize feature support

### ISSUE THREAD

**Issue by jonjburgess** [kraken-io/kraken-node#9]
Currently there doesn't seem to be any support in the package for the multi-resize feature. Seen here... http://disq.us/8myw0i 

I was just wondering if/when you were looking at implementation of the multi-resize feature into `kraken-node` as this would be extremely useful. :+1:

**Comment by crico** [comment]
Any updates on multiple resize?

**Comment by matylla** [comment]
Multi-resize is now live in production, please check the docs here - https://kraken.io/docs/image-resizing "Generating multiple sizes from a single input image". It boils down to this:

````js
var Kraken = require("kraken");
 
var kraken = new Kraken({
    "api_key": "your-api-key",
    "api_secret": "your-api-secret"
});
 
var params = {
    url: "http://awesome-website.com/images/header.png",
    wait: true,
    resize: [{
        id: "1",
        strategy: "fit",
        width: 100,
        height: 100
    },
    {
        id: "2",
        strategy: "crop",
        width: 300,
        height: 300
    },
    {
        id: "3",
        strategy: "square",
        size: 400
    }]
};
 
kraken.url(params, function (response) {
    if (response.success) {
        console.log(response.results);
    } else {
        console.log("Fail. Error message: %s", response.message);
    }
});
````
